#!/bin/bash
#clear

python GenerateCFG.py --rate=1M
python Distributed_GOP_v2.py --c=./Distributed_GOP_Config.cfg

#python GenerateCFG.py --rate=2M
#python Distributed_GOP_v2.py --c=./Distributed_GOP_Config.cfg

#python GenerateCFG.py --rate=4M
#python Distributed_GOP_v2.py --c=./Distributed_GOP_Config.cfg

#python GenerateCFG.py --rate=8M
#python Distributed_GOP_v2.py --c=./Distributed_GOP_Config.cfg

