#!/bin/bash
#clear

vid="Breathe3min"
W=1280
H=720

rlist="./OrderedFrames_Breathe3min_gp24.txt"
mcu=16
mpd=2
nf=4000
output_dir="../savenpy/"

## Target Bit Rate 
#opt=$vid
#qp=20;rate=50000;refa=32;refs=28;fps=8;fsr=1;mode=stitch;
#./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

#qp=20;rate=50000;refa=4;refs=0;fps=8;fsr=1;mode=normal;
#./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

###### Constant QP based (28)
opt=$vid
#qp=30;rate=0;refa=32;refs=28;fps=8;fsr=1;mode=stitch;
#./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

#qp=24;rate=0;refa=4;refs=0;fps=24;fsr=24;mode=normal;
#./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

qp=30;rate=0;refa=4;refs=0;fps=24;fsr=24;mode=normal;
./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr  --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

qp=36;rate=0;refa=4;refs=0;fps=24;fsr=24;mode=normal;
./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr  --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

qp=42;rate=0;refa=4;refs=0;fps=24;fsr=24;mode=normal;
./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr  --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

#vid="Breathe3min_320240"

#qp=24;rate=0;refa=4;refs=0;fps=24;fsr=24;mode=normal;
#./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr  --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

#qp=30;rate=0;refa=4;refs=0;fps=24;fsr=24;mode=normal;
#./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr  --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

#qp=36;rate=0;refa=4;refs=0;fps=24;fsr=24;mode=normal;
#./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr  --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

#qp=42;rate=0;refa=4;refs=0;fps=24;fsr=24;mode=normal;
#./Run_HMS_HoldFixPredictRPS_Rate_InterRPS --vid=$vid --W=$W --H=$H --rlist=$rlist --qp=$qp --rate=$rate --mcu=$mcu --mpd=$mpd --refa=$refa --refs=$refs --fps=$fps --fsr=$fsr  --nf=$nf --mode=$mode --output_dir=$output_dir --opt=$opt

