#!/bin/bash
#clear

vid="Breathe10sec_640480"
W=640
H=480

output_dir="../savenpy"
opt=''


ffmpeg -y -i ../vid/$vid.mp4 -vcodec rawvideo -pix_fmt yuv420p ../vid/$vid.yuv

## Target Bit Rate 
#opt='Test'
rate=20000;fps=24;
./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

#rate=40000;fps=24;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

#rate=100000;fps=24;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

#rate=200000;fps=24;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

#rate=300000;fps=24;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

#rate=400000;fps=24;
#./Run_VP9_Rate_ver0 --vid=$vid --W=$W --H=$H  --rate=$rate --fps=$fps --output_dir=$output_dir --opt=$opt

